### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [enjalot/algovis#20]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by vicapow** [comment]
Sounds like there would be a benefit in better curation of projects. It's a little ironic that this project itself is already a sort of curation of other projects, just not all of which are Github projects. Maybe adding this to project and others to some sort of showcase or landing page would be useful. It would also have the benefit of not requiring our or any other repos permission. Possibly an "Explorable Explanations" showcase in https://github.com/showcases?

**Comment by jeffreyjackson** [comment]
:+1:
