### ISSUE TITLE
Duplicate link

### ISSUE THREAD

**Issue by mootari** [enjalot/algovis#30]
Not sure if you care, but the spatial hashing links are actually duplicates:
* [Spatial Hashing](http://zufallsgenerator.github.io/2014/01/26/visually-comparing-algorithms/)
* [Comparison of spatial hashing algorithms](http://zufallsgenerator.github.io/2014/01/26/visually-comparing-algorithms/)

**Comment by enjalot** [comment]
i do care, thanks!
